import Head from 'next/head';
import Image from 'next/image';

import React, { useContext, useEffect, useState } from 'react';
import AuthContext from '../../context/auth/authContext';
import styled from 'styled-components';
import Router from 'next/router';

const Nav = styled.nav`
    background-color: var(--primary);
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0.5rem 1rem;

    p {
        color: var(--bluedark);
        font-size: 1.5rem;
        margin-left: 2rem;
        font-weight: 900;
    }

    button {
        margin-right: 1rem;
    }

    .logo {
        margin-left: 0.5rem;
        display: flex;
        align-items: center;
        img {
            cursor: pointer;
        }
    }
`;

const Footer = styled.footer`
    width: 100%;
    height: 100px;
    border-top: 1px solid #eaeaea;
    display: flex;
    justify-content: center;
    align-items: center;

    a {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-grow: 1;
    }
`;
export default function AppLayout({ children }) {
    const authContext = useContext(AuthContext);
    const { userAuth, LogOut, token } = authContext;

    const [isLoggedIn, setIsLoggedIn] = useState(null);
    useEffect(() => {
        setIsLoggedIn(token);
        return () => {
            setIsLoggedIn(null);
        };
    }, []);

    useEffect(() => {
        if (token) userAuth();
        else setIsLoggedIn(null);
    }, [token]);

    async function loggingOut() {
        await LogOut();
        Router.push('/');
    }
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Nav>
                    <div className="logo">
                        <span>
                            <Image
                                src="/logoMenu.svg"
                                alt="cuimo Logo"
                                width={75}
                                height={75}
                                onClick={() => Router.push('/')}
                            />
                        </span>
                    </div>
                    {isLoggedIn ? (
                        <>
                            <button
                                className="btn btn-primary cerrar-sesion"
                                onClick={() => loggingOut()}
                            >
                                Cerrar Sesión
                            </button>
                        </>
                    ) : (
                        <>
                            <button
                                className="btn btn-primary"
                                onClick={() => Router.push('/login')}
                            >
                                Iniciar Sesión
                            </button>
                        </>
                    )}
                </Nav>
                {children}
            </main>
            <Footer>
                <a
                    href="https://vercel.com"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className="logo">
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </Footer>
        </>
    );
}
